name: PlatformIO Build & Release

on:
  push:
    tags:
      - "v*"
      
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build all PlatformIO environments
        run: pio run

      - name: Rename firmware files to include environment name
        run: |
          for dir in .pio/build/*; do
            if [ -d "$dir" ]; then
              envname=$(basename "$dir")
              if [ -f "$dir/firmware.bin" ]; then
                mv "$dir/firmware.bin" "$dir/${envname}.bin"
              fi
              if [ -f "$dir/firmware.elf" ]; then
                mv "$dir/firmware.elf" "$dir/${envname}.elf"
              fi
            fi
          done

      - name: Upload all firmware to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            .pio/build/*/*.bin
            .pio/build/*/*.elf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
